import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Printer, ArrowLeft, BarChart } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { getFarms, getHarvestLots, getShipments, getBuyers } from '../services/api';

export default function ExportReport() {
  const navigate = useNavigate();
  
  const [buyers, setBuyers] = useState<any[]>([]);
  const [farms, setFarms] = useState<any[]>([]);
  const [lots, setLots] = useState<any[]>([]);
  const [shipments, setShipments] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [b, f, l, s] = await Promise.all([
          getBuyers(),
          getFarms(),
          getHarvestLots(),
          getShipments()
        ]);
        setBuyers(b);
        setFarms(f);
        setLots(l);
        setShipments(s);
      } catch (error) {
        console.error("Failed to fetch report data", error);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const handlePrint = () => {
    window.print();
  };

  const totalTonnage = lots.reduce((acc, lot) => acc + (lot.weight_tons || 0), 0);
  const deliveredShipments = shipments.filter(s => s.status === 'Delivered').length;
  const transitShipments = shipments.filter(s => s.status === 'In Transit').length;
  const plannedShipments = shipments.filter(s => s.status === 'Planned').length;

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="flex-1 overflow-auto bg-slate-100 absolute inset-0 z-50 flex flex-col items-center py-10 print:py-0 print:bg-white"
    >
      {/* Top Action Bar (Hidden when printing) */}
      <div className="w-full max-w-[850px] mb-6 flex items-center justify-between print:hidden">
        <button 
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-300 rounded-md hover:bg-slate-50 shadow-sm"
        >
          <ArrowLeft size={16} />
          Back to Dashboard
        </button>
        <div className="flex gap-3">
          <button 
            onClick={handlePrint}
            className="flex items-center gap-2 px-5 py-2 text-sm font-medium text-white bg-slate-900 rounded-md hover:bg-slate-800 shadow-sm"
          >
            <Printer size={16} />
            Print to PDF
          </button>
        </div>
      </div>

      {/* The Printable Document Paper */}
      <div className="w-full max-w-[850px] bg-white shadow-2xl print:shadow-none print:max-w-none print:w-full min-h-[1100px] relative px-16 py-20 font-serif text-slate-800">
        
        {/* Document Header */}
        <div className="flex justify-between items-start border-b-2 border-slate-900 pb-8 mb-8">
          <div>
            <h1 className="text-4xl font-bold tracking-tight text-slate-900 mb-2" style={{ fontFamily: 'Georgia, serif' }}>AGRIFLOW</h1>
            <p className="text-xs text-slate-500 uppercase tracking-[0.2em] font-sans font-semibold">Global Agri-Export Logistics</p>
          </div>
          <div className="text-right">
            <h2 className="text-2xl text-slate-400 font-light uppercase tracking-widest mb-4">Executive Summary Report</h2>
            <table className="w-full text-sm">
              <tbody>
                <tr>
                  <td className="py-1 pr-6 font-semibold text-slate-600 font-sans text-xs uppercase">Report Date:</td>
                  <td className="py-1 font-mono text-slate-900 font-bold">{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</td>
                </tr>
                <tr>
                  <td className="py-1 pr-6 font-semibold text-slate-600 font-sans text-xs uppercase">Generated By:</td>
                  <td className="py-1 font-mono text-slate-900">System Admin (Auto)</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        {loading ? (
          <div className="flex flex-col items-center justify-center py-20 text-slate-400">
            <BarChart className="animate-pulse mb-4" size={32} />
            <p>Compiling Telemetry Data...</p>
          </div>
        ) : (
          <>
            {/* KPI Summary Block */}
            <div className="grid grid-cols-4 gap-6 mb-12 border border-slate-200 bg-slate-50/50 p-6">
              <div>
                <h3 className="text-[10px] font-sans font-bold text-slate-500 uppercase tracking-widest mb-1">Total Harvest</h3>
                <p className="font-mono text-2xl font-bold text-slate-900">{totalTonnage.toFixed(1)} <span className="text-sm font-sans text-slate-500 font-medium">Tons</span></p>
              </div>
              <div className="border-l border-slate-200 pl-6">
                <h3 className="text-[10px] font-sans font-bold text-slate-500 uppercase tracking-widest mb-1">Active Farms</h3>
                <p className="font-mono text-2xl font-bold text-slate-900">{farms.length}</p>
              </div>
              <div className="border-l border-slate-200 pl-6">
                <h3 className="text-[10px] font-sans font-bold text-slate-500 uppercase tracking-widest mb-1">Total Shipments</h3>
                <p className="font-mono text-2xl font-bold text-slate-900">{shipments.length}</p>
              </div>
              <div className="border-l border-slate-200 pl-6">
                <h3 className="text-[10px] font-sans font-bold text-slate-500 uppercase tracking-widest mb-1">Active Buyers</h3>
                <p className="font-mono text-2xl font-bold text-slate-900">{buyers.length}</p>
              </div>
            </div>

            {/* Shipments Chart & Data */}
            <div className="mb-12">
              <h3 className="text-sm font-sans font-bold text-slate-800 uppercase tracking-widest border-b-2 border-slate-900 pb-2 mb-6">Shipment Pipeline Analysis</h3>
              
              <div className="flex items-center gap-8 mb-8 font-sans">
                {/* Visual Chart (CSS Based) */}
                <div className="w-48 h-48 rounded-full border-[16px] border-slate-100 relative flex items-center justify-center">
                  {/* Fake donut chart segments */}
                  <div className="absolute inset-[-16px] rounded-full border-[16px] border-blue-600" style={{ clipPath: 'polygon(50% 50%, 100% 0, 100% 100%, 0 100%, 0 0, 20% 0)' }}></div>
                  <div className="absolute inset-[-16px] rounded-full border-[16px] border-emerald-500" style={{ clipPath: 'polygon(50% 50%, 0 0, 50% 0)' }}></div>
                  <div className="text-center">
                    <p className="text-3xl font-bold text-slate-900">{shipments.length}</p>
                    <p className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Total</p>
                  </div>
                </div>

                <div className="flex-1 space-y-4">
                  <div className="flex items-center justify-between border-b border-slate-200 pb-2">
                    <div className="flex items-center gap-3">
                      <span className="w-3 h-3 bg-slate-200 rounded-full"></span>
                      <span className="text-sm font-semibold text-slate-700">Planned</span>
                    </div>
                    <span className="font-mono font-bold text-slate-900">{plannedShipments}</span>
                  </div>
                  <div className="flex items-center justify-between border-b border-slate-200 pb-2">
                    <div className="flex items-center gap-3">
                      <span className="w-3 h-3 bg-blue-600 rounded-full"></span>
                      <span className="text-sm font-semibold text-slate-700">In Transit</span>
                    </div>
                    <span className="font-mono font-bold text-slate-900">{transitShipments}</span>
                  </div>
                  <div className="flex items-center justify-between border-b border-slate-200 pb-2">
                    <div className="flex items-center gap-3">
                      <span className="w-3 h-3 bg-emerald-500 rounded-full"></span>
                      <span className="text-sm font-semibold text-slate-700">Delivered</span>
                    </div>
                    <span className="font-mono font-bold text-slate-900">{deliveredShipments}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Harvest Lots Table */}
            <div className="mb-12 font-sans">
              <h3 className="text-sm font-sans font-bold text-slate-800 uppercase tracking-widest border-b-2 border-slate-900 pb-2 mb-6">Recent Harvest Lots Inventory</h3>
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-slate-900 text-white text-[11px] uppercase tracking-wider">
                    <th className="py-3 px-4 font-semibold rounded-tl-sm">Lot ID</th>
                    <th className="py-3 px-4 font-semibold">Origin Farm</th>
                    <th className="py-3 px-4 font-semibold text-right">Volume</th>
                    <th className="py-3 px-4 font-semibold">Quality Grade</th>
                    <th className="py-3 px-4 font-semibold rounded-tr-sm">Facility Status</th>
                  </tr>
                </thead>
                <tbody className="text-[13px] divide-y divide-slate-200 border-b-2 border-slate-900">
                  {lots.slice(0, 8).map(lot => (
                    <tr key={lot.id}>
                      <td className="py-3 px-4 font-mono font-medium text-slate-700">{lot.id}</td>
                      <td className="py-3 px-4 text-slate-900">{lot.farm_id}</td>
                      <td className="py-3 px-4 text-right font-medium text-slate-900">{lot.weight_tons} T</td>
                      <td className="py-3 px-4">
                        <span className="px-2 py-0.5 border border-slate-200 bg-slate-50 rounded text-[11px] font-semibold text-slate-600">
                          {lot.quality_grade || 'Pending'}
                        </span>
                      </td>
                      <td className="py-3 px-4">
                        <span className="text-slate-600 font-medium">
                          {lot.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                  {lots.length === 0 && (
                    <tr>
                      <td colSpan={5} className="py-8 text-center text-slate-500 italic">No harvest lots recorded yet.</td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>

            {/* Footnote */}
            <div className="mt-16 pt-8 border-t border-slate-200 text-center">
              <p className="text-[10px] text-slate-400 uppercase tracking-widest font-sans font-semibold">
                CONFIDENTIAL — Internal Distribution Only
              </p>
              <p className="text-[11px] text-slate-500 mt-2 italic">
                Data compiled directly from AgriFlow PostgreSQL database and IoT telemetry endpoints.
              </p>
            </div>
          </>
        )}
      </div>
    </motion.div>
  );
}
